### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by imerdell-55** [jeasion/wolai-alfred#1]
已打赏5块，先说背景，最近一直想从notion把笔记迁移出去，搜了下发现有这个workflow，遂下定了决心用wolai。看了下这个workflow开出来的时间也是最近，真的是机缘巧合。刚刚试了下过了遍代码发现有几个小问题，也可能是作者个人的使用习惯。
1.  [Wolai.py 86行](https://github.com/jeasion/wolai-alfred/blob/7dfcaaf2b3dea54f84e683f6ffcac24bda71b6d4/src/wolai.py#L86) append 缩进问题会导致没有没有图标的结果搜不到，也许是作者自己只想搜索带图标的文件。
2.  检索到打开文件过程是通过获取id来拼接文件url实现的，因为开了模糊搜索，所以返回的结果id不一定是page_id，会导致一些跳转失效，建议使用page_id。
3.  同样是因为模糊搜索，当一个页面出现多次关键词时视为多个检索结果，在搜索返回时可能会出现多个同一页面，建议随手加个set()滤一下。

**Comment by jeasion** [comment]
> 已打赏5块，先说背景，最近一直想从notion把笔记迁移出去，搜了下发现有这个workflow，遂下定了决心用wolai。看了下这个workflow开出来的时间也是最近，真的是机缘巧合。刚刚试了下过了遍代码发现有几个小问题，也可能是作者个人的使用习惯。
> 
> 1. [Wolai.py 86行](https://github.com/jeasion/wolai-alfred/blob/7dfcaaf2b3dea54f84e683f6ffcac24bda71b6d4/src/wolai.py#L86) append 缩进问题会导致没有没有图标的结果搜不到，也许是作者自己只想搜索带图标的文件。
> 2. 检索到打开文件过程是通过获取id来拼接文件url实现的，因为开了模糊搜索，所以返回的结果id不一定是page_id，会导致一些跳转失效，建议使用page_id。
> 3. 同样是因为模糊搜索，当一个页面出现多次关键词时视为多个检索结果，在搜索返回时可能会出现多个同一页面，建议随手加个set()滤一下。

非常感谢打赏以及建议，个人只是在群里看到有人提这个，顺手就给做了。
本来只是坐着玩的，没想到真有人用，还给我打赏。
加上本人是JAVA程序员，并不懂python，基本就是对着Python的文档抄的，而且wolai的API还没文档，基本就是自己抓包分析的，做的很beta，非常感谢你的建议。五一我弄个版本改下。

**Comment by jeasion** [comment]
新版本已修改
